name: ReleaseDate
description: ReleaseDate project.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0
  firebase_database: ^3.0.5
  firebase_admob: ^0.9.0+3
  shared_preferences: 0.4.3
  cached_network_image: ^1.0.0
  image_picker: ^0.6.0+10
  share: ^0.6.1+1
  url_launcher: ^5.0.3
  http: ^0.12.0+2
  flutter_local_notifications: ^0.7.1+3
  flutter_launcher_icons: ^0.7.2+1
  sqflite: ^1.1.6+1
  intl: 0.15.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0

flutter_icons:
  image_path: 'icon/icon.png'
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/dummyImage.jpeg
    - assets/platforms/nintendo.png
    - assets/platforms/pc.png
    - assets/platforms/ps4.png
    - assets/platforms/xbox.png
    - assets/brand.png
    - assets/novideo.png
    - assets/noimageavailable.png
    - icon/icon.png
